#!/usr/bin/env bash
# install nginx on my remote server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html

#Give the user  ownership to website files
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
new_string='server_name _;\n\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/'
sudo sed -i "s/server_name _;\$/${new_string}" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
