#!/usr/bin/env bash
# Install and configure HAproxy on lb-01
apt update
apt -y install haproxy
echo -e "\n# Set ENABLED to 1 if you want the init script to start haproxy." >> /etc/default/haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo -e "\nfrontend www\n\tbind *:80" >> /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web-backend\n\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver web1 100.26.219.114:80 check" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver web2 35.175.129.54:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
